boat:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  sail_controller:
    type: position_controllers/JointPositionController
    joint: mast_sail_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
  rudder_controller:
    type: position_controllers/JointPositionController
    joint: holder_rudder_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
